### PR TITLE
[DO NOT MERGE] workflow for "stage 2" of bootstrapping

### PR DESCRIPTION
**Pull request by jeremyd2019**
- "stage 1" of bootstrapping is done by the workflow on the "bootstrap" branch, which builds the packages on that branch.
- "stage 2" is this new workflow, which uses the output of "stage 1" to builds enough packages to build the MINGW-packages version of mingw-w64-clang, with hacks to reduce dependencies/eliminate circular dependencies.
- The results of "stage 2" are enough to build the same set of MINGW-packages __without__ the hacks applied on stage 2.  This could either be a "stage 3" of bootstrapping, or msys2-autobuild could be turned loose to rebuild all packages using these.
  - There is one patch which in here which is not a hack, and _is_ actually required, which is msys2/MINGW-packages#8192

This is intended to be a new branch, but on second thought could theoretically be added to the 'bootstrap' branch without issue (probably moving files around to make less of a mess).  Let me know what's preferred.

### CODE REVIEW

**Comment by jeremyd2019** [comment]
Note that CLANG32 does not build due to #34, and CLANGARM64 cannot build on x86 hosted runners

**Comment by jeremyd2019** [comment]
I managed to get a test branch to finish CLANG64 _and_ CLANG32 by setting `!makeflags` on openssl and python.  I'll push changes here if another run succeeds

**Comment by jeremyd2019** [comment]
I've managed to get my first run through stage 2 and 3 on my fork.  I plan to rebase/squash some commits, push the new branches, and start the workflows on this repo.
I also plan to start building arm64 packages "from scratch" from the clang which was built on the 'bootstrap' workflow, and upload the results manually to releases on this repo, if that's OK @lazka .
My expectation is that the results of "stage 3" would be used to seed the official repos, and would hopefully be enough to let msys2-autobuild be able to start building more packages.

**Comment by lazka** [comment]
sure

**Comment by jeremyd2019** [comment]
Pushed

**Comment by jeremyd2019** [comment]
Renaming the workflow yaml file didn't work - `gh workflow run` said it couldn't find it, so force-pushed back to main.yml, but with a name: attribute change.  That seems to have done the trick for putting that name in the Actions list, which is what was bugging me most.  🚀

**Comment by jeremyd2019** [comment]
@lazka @mati865 Both "stage 2" and "stage 3" (https://github.com/msys2/CLANG-packages/tree/bootstrap-stage3) workflows have successfully finished and uploaded their packages, for clang32 and clang64! 🎉
I believe "stage 3" packages can now be used to initialize the "official" repos, and start letting msys2-autobuild get to work.

Note that these were built off of MINGW-packages master at the time they were run, with the changes from msys2/MINGW-packages#8192 applied, plus patching openssl and python PKGBUILDs to set `!makeflags` to help work around #34.

```ini
[clang32]
Server = https://github.com/msys2/CLANG-packages/releases/download/bootstrap-stage3-clang32/
SigLevel = Never

[clang64]
Server = https://github.com/msys2/CLANG-packages/releases/download/bootstrap-stage3-clang64/
SigLevel = Never
```

**Comment by jeremyd2019** [comment]
I am building ARM64 packages on my raspberry pi, but don't expect to finish stage 3 for a week or two 🐢

**Comment by Biswa96** [comment]
Which pi are you using? And what is the storage drive?
Tip: Removing Windows Defender will speed up things many times.

**Comment by jeremyd2019** [comment]
Pi 3B+, and a 64GB SanDisk MicroSD (I've heard that USB storage might be faster, but don't have any handy).  I've disabled Windows Defender as best I can via group policy, without resorting to 3rd party scripts that yank it out forcefully

**Comment by lazka** [comment]
`clang64` is ready now. I haven't done anything re clang32.

**Comment by Biswa96** [comment]
Is 32bit required?

**Comment by mati865** [comment]
Fantastic work everyone, especially @jeremyd2019!

Let's notify @mstorsjo as he will be happy to hear about it.
After installing Clang subsystem with `pacman -S --needed mingw-w64-clang-x86_64-toolchain`:
```
mateusz@DESKTOP-MATI CLANG64 /d/tmp
$ c++ hello.cpp -v
clang version 11.0.0
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: D:/msys64/clang64/bin
 "D:/msys64/clang64/bin/c++.exe" -cc1 -triple x86_64-w64-windows-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name hello.cpp -mrelocation-model pic -pic-level 2 -mframe-pointer=none -fmath-errno -fno-rounding-math -mconstructor-aliases -mms-bitfields -munwind-tables -target-cpu x86-64 -debugger-tuning=gdb -v -resource-dir D:/msys64/clang64/lib/clang/11.0.0 -internal-isystem D:/msys64/clang64/x86_64-w64-mingw32/include/c++/v1 -internal-isystem D:/msys64/clang64/include/c++/v1 -internal-isystem D:/msys64/clang64/lib/clang/11.0.0/include -internal-isystem D:/msys64/clang64/x86_64-w64-mingw32/include -internal-isystem D:/msys64/clang64/include -fdeprecated-macro -fdebug-compilation-dir "D:\\tmp" -ferror-limit 19 -fno-use-cxa-atexit -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fseh-exceptions -faddrsig -o "D:\\msys64\\tmp/hello-994e1e.o" -x c++ hello.cpp
clang -cc1 version 11.0.0 based upon LLVM 11.0.0 default target x86_64-w64-mingw32
ignoring nonexistent directory "D:/msys64/clang64/x86_64-w64-mingw32/include/c++/v1"
#include "..." search starts here:
#include <...> search starts here:
 D:/msys64/clang64/include/c++/v1
 D:/msys64/clang64/lib/clang/11.0.0/include
 D:/msys64/clang64/x86_64-w64-mingw32/include
 D:/msys64/clang64/include
End of search list.
 "D:/msys64/clang64/bin/ld.lld" -m i386pep -Bdynamic -o a.exe D:/msys64/clang64/x86_64-w64-mingw32/lib/crt2.o D:/msys64/clang64/x86_64-w64-mingw32/lib/crtbegin.o -LD:/msys64/clang64/x86_64-w64-mingw32/lib -LD:/msys64/clang64/lib -LD:/msys64/clang64/x86_64-w64-mingw32/sys-root/mingw/lib -LD:/msys64/clang64/lib/clang/11.0.0/lib/windows "D:\\msys64\\tmp/hello-994e1e.o" -lc++ -lmingw32 D:/msys64/clang64/lib/clang/11.0.0/lib/windows/libclang_rt.builtins-x86_64.a -l:libunwind.dll.a -lmoldname -lmingwex -lmsvcrt -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 D:/msys64/clang64/lib/clang/11.0.0/lib/windows/libclang_rt.builtins-x86_64.a -l:libunwind.dll.a -lmoldname -lmingwex -lmsvcrt -lkernel32 D:/msys64/clang64/x86_64-w64-mingw32/lib/crtend.o

mateusz@DESKTOP-MATI CLANG64 /d/tmp
$ ntldd a.exe
        libc++.dll => D:\msys64\clang64\bin\libc++.dll (0x0000000000770000)
        libunwind.dll => D:\msys64\clang64\bin\libunwind.dll (0x00000000004f0000)
        KERNEL32.dll => C:\Windows\SYSTEM32\KERNEL32.dll (0x0000000000890000)

mateusz@DESKTOP-MATI CLANG64 /d/tmp
$ ./a.exe
Hello
```

The repository is pretty basic right now (it's bootstrap after all) but will be populated with more packages as the time goes. We will have to upgrade to LLVM 12 and integrate https://github.com/mstorsjo/llvm-mingw/commit/2094638569e9c684fa71d0e36d259c35ae55357b
We have new LLVM/Clang specific patches for:
- LLVM https://github.com/msys2/CLANG-packages/blob/bootstrap/mingw-w64-clang/0001-Use-posix-style-path-separators-with-MinGW.patch
- Clang https://github.com/msys2/CLANG-packages/blob/bootstrap/mingw-w64-clang/0103-Use-posix-style-path-separators-with-MinGW.patch
- libtool https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-libtool/0014-Support-llvm-objdump-f-output.patch

**Comment by mati865** [comment]
LLDB also looks good (for now it has to be called through `winpty` when using MinTTY):
```
mateusz@DESKTOP-MATI CLANG64 /d/tmp
$ cat crash.c
int main() {
    int a[1] = {1};
    a[1024] = 2;
}

$ cc crash.c
crash.c:3:5: warning: array index 1024 is past the end of the array (which contains 1 element) [-Warray-bounds]
    a[1024] = 2;
    ^ ~~~~
crash.c:2:5: note: array 'a' declared here
    int a[1] = {1};
    ^
1 warning generated.

mateusz@DESKTOP-MATI CLANG64 /d/tmp
$ ./a.exe
Segmentation fault

mateusz@DESKTOP-MATI CLANG64 /d/tmp
$ winpty lldb a.exe
(lldb) target create "a.exe"
Current executable set to 'D:\tmp\a.exe' (x86_64).
(lldb) r
Process 7820 launched: 'D:\tmp\a.exe' (x86_64)
Process 7820 stopped
* thread #1, stop reason = Exception 0xc0000005 encountered at address 0x14000149a: Access violation writing location 0x00150e2c
    frame #0: 0x000000014000149a a.exe`main + 26
a.exe`main:
->  0x14000149a <+26>: movl   $0x2, 0xffc(%rbp)
    0x1400014a4 <+36>: addq   $0x30, %rsp
    0x1400014a8 <+40>: popq   %rbp
    0x1400014a9 <+41>: retq
(lldb) bt
* thread #1, stop reason = Exception 0xc0000005 encountered at address 0x14000149a: Access violation writing location 0x00150e2c
  * frame #0: 0x000000014000149a a.exe`main + 26
    frame #1: 0x00000001400013ea a.exe`__tmainCRTStartup at crtexe.c:321:15
    frame #2: 0x0000000140001446 a.exe`mainCRTStartup at crtexe.c:202:9
    frame #3: 0x00007fffaea87034 kernel32.dll`BaseThreadInitThunk + 20
    frame #4: 0x00007fffaf722651 ntdll.dll`RtlUserThreadStart + 33
(lldb) d
a.exe`main:
    0x140001480 <+0>:  pushq  %rbp
    0x140001481 <+1>:  subq   $0x30, %rsp
    0x140001485 <+5>:  leaq   0x30(%rsp), %rbp
    0x14000148a <+10>: callq  0x140001560               ; __main at gccmain.c:54
    0x14000148f <+15>: xorl   %eax, %eax
    0x140001491 <+17>: movl   0x1c09(%rip), %ecx        ; .rdata
    0x140001497 <+23>: movl   %ecx, -0x4(%rbp)
->  0x14000149a <+26>: movl   $0x2, 0xffc(%rbp)
    0x1400014a4 <+36>: addq   $0x30, %rsp
    0x1400014a8 <+40>: popq   %rbp
    0x1400014a9 <+41>: retq
    0x1400014aa <+42>: int3
    0x1400014ab <+43>: int3
    0x1400014ac <+44>: int3
    0x1400014ad <+45>: int3
    0x1400014ae <+46>: int3
    0x1400014af <+47>: int3
(lldb) q
Quitting LLDB will kill one or more processes. Do you really want to proceed: [Y/n]
```

With debug info (`cc -g crash.c`):
```
$ winpty lldb a.exe
(lldb) target create "a.exe"
Current executable set to 'D:\tmp\a.exe' (x86_64).
(lldb) r
Process 14692 launched: 'D:\tmp\a.exe' (x86_64)
Process 14692 stopped
* thread #1, stop reason = Exception 0xc0000005 encountered at address 0x14000149a: Access violation writing location 0x00150e2c
    frame #0: 0x000000014000149a a.exe`main at crash.c:3:13
   1    int main() {
   2        int a[1] = {1};
-> 3        a[1024] = 2;
   4    }
```

**Comment by jeremyd2019** [comment]
> Is 32bit required?

Required for what?  By whom?

> `clang64` is ready now. I haven't done anything re clang32.

Any thoughts on 'experimental' repos?  Maybe they exist but aren't in pacman.conf (or are commented out by default).

**Comment by Biswa96** [comment]
I asked if `/clang32` packages are required or not.

**Comment by lazka** [comment]
> Any thoughts on 'experimental' repos? Maybe they exist but aren't in pacman.conf (or are commented out by default).

That's certainly possible. It would still require us to build everything for it etc... but since it's you that's asking....

@mati865  @mstorsjo what are your thoughts on 32bit? Would having a MSYS2 repo providing it give you any value?

**Comment by mati865** [comment]
Maintenance will take (possibly much) more effort than other architectures but if jeremyd2019 wants to do it I won't stop him.
My only concern is repository size which will affect our mirrors. Maybe such experimental repos could be hosted only in 1-2 places?

**Comment by mstorsjo** [comment]
> Fantastic work everyone, especially @jeremyd2019!
> 
> Let's notify @mstorsjo as he will be happy to hear about it.

Awesome! Nice work guys.


> LLDB also looks good

Great! For a slightly larger smoke test for LLDB, I'm using https://github.com/mstorsjo/llvm-mingw/blob/master/test/hello-exception.cpp, invoked with either `-crash` or `-breakpoint`. That way you can e.g. check that you have a meaningful backtrace.

> (for now it has to be called through `winpty` when using MinTTY):

Ah, nice, I didn't know about that - I've had to resort to running it in cmd.exe to work sensibly.

> @mati865 @mstorsjo what are your thoughts on 32bit? Would having a MSYS2 repo providing it give you any value?

No big difference for me. I guess it doesn't add much end user value, but might be nice for completeness/curiosity.

For the packages I cross build regularly, I try to keep all 4 architectures on par with each other - so i386 is supposed to work, but if building larger number of packages I guess there'll be a bit more issues to work through.

**Comment by lazka** [comment]
I'm willing to add it without exposing it too much, and we can see how it works out in CI etc.

**Comment by lazka** [comment]
`clang32` is now handled by autobuild for starters

**Comment by jeremyd2019** [comment]
> I am building ARM64 packages on my raspberry pi, but don't expect to finish stage 3 for a week or two 🐢

Stage 3 of aarch64 is done now

**Comment by lazka** [comment]
Should I prepare a repo etc?

**Comment by jeremyd2019** [comment]
I don't know.  Manually building on my raspberry pi is not very sustainable, especially if more packages are being built/updated.  I was thinking a bit about the self-hosted runner for GHA, but with the @#$# pacman deadlock I get that'd still require a lot of manual intervention (killing the offending pacman.exe in task manager)

**Comment by lazka** [comment]
ok, yeah, tricky. I was just thinking upload and leave it, so it's easier to pick up once things improve.

**Comment by jeremyd2019** [comment]
If you like.  I plan to build newer packages next week, after Tuesday's updates, and try to catch up.

**Comment by jeremyd2019** [comment]
I built updated packages through msys2/MINGW-packages@14259b4cf and uploaded to the same release.  I plan to start the build of llvm 12 after Patch Tuesday, and I'll continue to upload to that release

**Comment by lazka** [comment]
> ok, yeah, tricky. I was just thinking upload and leave it, so it's easier to pick up once things improve.

for future reference, this is now done.

**Pull request closed without merging**
