### PR TITLE
add gha workflow to build bootstrap packages

### PR DESCRIPTION
**Pull request by jeremyd2019**
Builds CLANG32 and CLANG64.

These packages can then be used to build a subset of MINGW-packages hacked to minimize dependencies/break circular dependencies, then those can be used to build real packages.

### CODE REVIEW

**Comment by jeremyd2019** [comment]
I am also thinking about 'publishing' the packages as a repo after the build, ie using `eine/tip`.  My understanding is that these packages are not really meant to hang around, just be used to bootstrap 'real' packages, so may not make sense to publish and be mirrored like 'real' packages.

**Comment by Biswa96** [comment]
How about adding the ci builds to mingw-packages repo using `mingw-arch=(clang64)`?

**Comment by jeremyd2019** [comment]
That's the ultimate goal, but first things need to be 'bootstrapped', first the compiler/linker/core libs (this repo), then sufficient build tools to be able to build packages from MINGW-packages.  I've already done this locally for `CLANG32` and `CLANGARM64` but I figured the best way to help move things forward for the project would be to try to automate building each 'bootstrap' phase in GHA.

**Comment by jeremyd2019** [comment]
My previous comment about 'publishing' was about making the results of this phase of bootstrapping available to the next.

**Comment by mati865** [comment]
UCRT packages were bootstrapped manually by @lazka, this approach seems more transparent but I'd be fine with either way.

**Comment by lazka** [comment]
All fine with me. I had to do various hacks to get things to build... but I appreciate the goal to make it less hacky.

Do we really want clang32 though? (I know your hardware BIOS limitations.. sry)

**Comment by smalltalkman** [comment]
There are now [MSYS2-packages/clang](https://github.com/msys2/MSYS2-packages/tree/master/clang), [MSYS2-packages/mingw-w64-cross-clang](https://github.com/msys2/MSYS2-packages/tree/master/mingw-w64-cross-clang), [MINGW-packages/mingw-w64-clang](https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-clang), [CLANG-packages/tree/bootstrap/mingw-w64-clang](https://github.com/msys2/CLANG-packages/tree/bootstrap/mingw-w64-clang). Why is there so much clang? What is the difference between them? Under what circumstances should we use these different versions of clang?

**Comment by lazka** [comment]
egg bacon and clang, egg bacon sausage and clang, clang bacon sausage and clang, clang clang clang... :P

**Comment by jeremyd2019** [comment]
A normal user should be using  [MINGW-packages/mingw-w64-clang](https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-clang).

The others are being used to bootstrap a new environment that uses clang rather than gcc.  The main reason this needs to be a new environment is that it will use clang's libc++ instead of gcc's libstdc++, and also use native Windows TLS instead of gcc's emutls (gcc apparently never got a native Windows TLS implementation).  So there's a possibility that C++ things, or things that use C11 thread_local, would not be compatible.

**Comment by jeremyd2019** [comment]
As far as clang32, I mostly played with it because @mati865 implied it couldn't be done 😝 .  If it's the consensus that 32-bit is not worth the cycles/bandwidth for the project proper that's fine, but don't be surprised if I still make PRs to fix things for it from time to time 😉

**Comment by mati865** [comment]
> As far as clang32, I mostly played with it because @mati865 implied it couldn't be done 

TBH I've spent hours on that last year and couldn't manage to link LLVM with 32-bit LLD getting `LLVM ERROR: out of memory` (because of memory mapped IO). Upstream LLD developers all said the solution is to use 64-bit LLD.

I have no idea how it builds now, maybe less compilation/linkage threads?

---

I have nothing against 32-bit Clang subsystem as long as it's not advertised as "officially" supported. It will have hard time linking huge packages (Qt I'm looking at you) and probably won't be able to build itself again at some point.
That way when the time comes it'll be easier for MSYS2 to abandon something it can no longer support without rewriting LLD IO.

**Comment by jeremyd2019** [comment]
rebased, and added 'publish' to github releases for pushes to branches.

**Comment by mati865** [comment]
I have no clue about these scripts and no objections either.

@lazka?

**Comment by lazka** [comment]
sure, go ahead.. If there are any packages to upload to the man repo, let me know.

**Comment by jeremyd2019** [comment]
> I have nothing against 32-bit Clang subsystem as long as it's not advertised as "officially" supported. It will have hard time linking huge packages (Qt I'm looking at you) and probably won't be able to build itself again at some point.
> That way when the time comes it'll be easier for MSYS2 to abandon something it can no longer support without rewriting LLD IO.

I was trying to build some bootstrap packages in a GHA, and 32-bit Clang is failing there linking openssl consistently.  ~~Oddly, have not had any such issue on my local VM.~~ It has suddenly decided to start failing on my local VM now too.  `libc++abi: terminating with uncaught exception of type std::__1::system_error: thread constructor failed: Exec format error`  The stack trace always seems to have `_ZN3lld4coff12LinkerDriver11enqueuePathEN4llvm9StringRefEbb` as the entry before the exception is thrown.  "Exec format error" seems like an interesting reason for a thread constructor to fail.

**Comment by mati865** [comment]
Indeed interesting reason.
@jeremyd2019 what is your opinion on uploading bootstrap packages to main repo? IMO we should rebuilt them once https://github.com/msys2/MSYS2-packages/pull/2294 lands and get them in the main repo.

**Comment by jeremyd2019** [comment]
Once that PR is done #2 can be merged, and then the results of that could be uploaded if desired.  I have been playing with making a GHA/script to bootstrap/build enough packages so that MINGW-packages/mingw-w64-clang can be built (after msys2/MINGW-packages#8192 is merged).  After that there should be enough to enable building unmodified packages from MINGW-packages.

**Pull request merged**
